language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: setup=lowest
    - php: 7.1
      env: setup=highest
    - php: 7.2
      env: setup=lowest
    - php: 7.2
      env: setup=highest
    - php: nightly
      env: setup=lowest
    - php: nightly
      env: setup=highest
  allow_failures:
    - php: nightly

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version
  - pecl install -f parle
  - echo "extension=parle.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update -q
  - if [ -z "$setup" ]; then composer install; fi;
  - if [ "$setup" = "lowest" ]; then composer update --prefer-lowest --no-interaction --prefer-dist --no-suggest; fi;
  - if [ "$setup" = "highest" ]; then composer update --no-interaction --prefer-dist --no-suggest; fi;

script: vendor/bin/phpunit
